version: '3.8'

services:
  streamlit-app:
    container_name: streamlit
    build:
      context: streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-app
    environment:
      - STREAMLIT_SERVER_PORT=8501
    networks:
      - app-network

  fastapi-app:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - UVICORN_HOST=127.0.0.1
      - UVICORN_PORT=9000
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "9000" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
